theme: jekyll-theme-cayman
description: Profiles, Projects, and Interests for the UH Community
show_downloads: true
github:
  is_project_page: true
  repository_url: https://trigeeks.github.io/bowfoliosApp.github.io/
social:
  type: Organization
gems:
  - jekyll-mentions
